spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=PetAdoptDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=Admin1234*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always