# Conexión a la base de datos SQL Server Express
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PetAdoptDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Admin1234*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true